# Generated by Django 6.1.1 on 2026-09-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('roll_number', 'classroom'), name='unique_roll_number_per_class'),
        ),
    ]
